### PR TITLE
Update sample table parsing, add `Project.remove_samples` (2)

### PR DESCRIPTION
**Pull request by nleroy917**
I wasn't able to push to Michal's branch. So I just forked it and added a new branch to `origin`. Here are his original PR notes:

> Work in progress...

- more flexible sample table selection strategy
- add XLSX sample table parser
- add `Project.remove_samples` method

See here for everything: https://github.com/pepkit/peppy/pull/374

### CODE REVIEW

**Comment by nleroy917** [comment]
@nsheff @Khoroshevskyi @rafalstepien I ended up just creating a new branch on `origin` since I wasn't able to make changes to Michal's personal branch to resolve merge conflicts... I am **not** 100% sure I did everything correctly, however. I am a bit afraid to merge this into dev for fear of blowing away everything we did previously. There are no unit tests to test for this.

If people could give me a sanity check that merging into `dev` won't steamroll the `from_dict` changes, that would be helpful.

**Comment by Khoroshevskyi** [comment]
My thoughts about merging this two branches: create new branch from dev and then create pull request from michal_changes to this new branch. Next push new changes to dev branch and then to master

**Comment by nleroy917** [comment]
Looking at the files, all the equality and `from_dict` stuff is here. So, it might be good to go

**Comment by nleroy917** [comment]
@rafalstepien could you confirm your stuff for optimization is here? Then I will merge to dev.

**Comment by rafalstepien** [comment]
My changes were merged to `dev` at July 18-th. Please see [commits history](https://github.com/pepkit/peppy/commits/dev).

**Pull request merged**
