### PR TITLE
0.22.0

### PR DESCRIPTION
**Pull request by nsheff**
In support of looper 0.12.2

We need to get a functioning release version of looper.

Milestone issues: https://github.com/pepkit/peppy/milestone/12

### CODE REVIEW

**Comment by nsheff** [comment]
is this ready to be merged/released?

**Comment by nsheff** [comment]
I'd like to merge this today. Does this incorporate the index flexibility requested in https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/pull/8#issuecomment-497109854 ?

**Comment by vreuter** [comment]
> I'd like to merge this today. Does this incorporate the index flexibility requested in [snakemake-workflows/dna-seq-gatk-variant-calling#8 (comment)](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/pull/8#issuecomment-497109854) ?

It will include the indexing. I have no plans to remove `SnakeProject` because I so fundamentally disagree with the preference against subclassing that we can discuss that separately. It was evident that removing that class was a motivation for some of the other suggestions, so it should've been made up front, rather than backdooring the design preference.

**Comment by nsheff** [comment]
agreed, leave it for now, I think it's useful.

**Comment by nsheff** [comment]
is this good to go?

**Comment by vreuter** [comment]
Yeah

**Pull request merged**
